name: Deploy para C3SL UFPR

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Resolve o aviso do GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar e Build
        run: |
          npm install
          npm run build

      - name: Enviar para o Servidor via SCP
        uses: appleboy/scp-action@master
        with:
          host: farma-alg-ia.c3sl.ufpr.br
          username: yrgfeitosa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/home/yrgfeitosa/public_html/dashboard"
          strip_components: 1
          overwrite: true # Garante que ele substitua arquivos antigos