name: Deploy para C3SL UFPR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Força o uso do Node mais recente
        with:
          node-version: '24'

      - name: Instalar e Build
        run: |
          npm install
          npm run build

      - name: Enviar para o Servidor via SCP
        uses: appleboy/scp-action@master
        with:
          host: farma-alg-ia.c3sl.ufpr.br
          username: seu_usuario_c3sl
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/caminho/no/servidor/dashboard"
          strip_components: 1